name: iOrderBook - Pull Request Validation

on:
  push:
    branches: [
      'main'
    ]

jobs:
  idatabook-angular-v18-pr-validation-job:
    name: iOrderBook - Angular v18 - Pull Request Validation
    runs-on: ubuntu-latest
    
    steps:
    - name: Checking-out Code
      uses: actions/checkout@v4

    - name: Setting-up Node Environment
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    
    - name: Restoring Dependencies
      working-directory: ./Angular.v18
      run: npm ci
    
    - name: Build
      working-directory: ./Angular.v18
      run: npm run build
  
  idatabook-react-v18-pr-validation-job:
    name: iOrderBook - React v18 - Pull Request Validation
    runs-on: ubuntu-latest
    
    steps:
    - name: Checking-out Code
      uses: actions/checkout@v4

    - name: Setting-up Node Environment
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    
    - name: Restoring Dependencies
      working-directory: ./React.v18
      run: npm ci
    
    - name: Build
      working-directory: ./React.v18
      run: npm run build