name: iOrderBook - Pull Request Validation

on:
  push:
    branches: [
      'main'
    ]

jobs:
  idatabook-pr-validation-job:
    name: iOrderBook - Pull Request Validation
    runs-on: ubuntu-latest
    
    steps:
    - name: Checking-out Code
      uses: actions/checkout@v4

    - name: Setting-up Node Environment
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    
    - name: Restoring Dependencies
      run: npm ci
    
    - name: Build
      run: npm run build