name: iOrderBook - Publish to Github Pages

on:
  push:
    tags:
      - publish/v*.*.*

jobs:
  idatabook-publish-to-github-pages-job:
    name: iOrderBook - Publish to Github Pages
    runs-on: ubuntu-latest
    
    steps:
    - name: Checking-out Code
      uses: actions/checkout@v4

    - name: Setting-up Node Environment
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    
    - name: Restoring Dependencies
      run: npm ci
    
    - name: Build
      run: npm run build
    
    - name: Publish
      run: npm run publish